services:
  mysql:
    image: mysql:8.0
    container_name: ecp_mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123258789
      MYSQL_DATABASE: ecp_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123258789
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecp_network
    restart: always

networks:
  ecp_network:
    driver: bridge

volumes:
  mysql_data:
