services:
  api:
    image: ghcr.io/thanhnguyenhoang171/ecp/ecp-api:latest
    container_name: ecp_api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '9091:9090'
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_MONGODB_URI: ${SPRING_MONGODB_URI}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_REDIS_USERNAME: ${SPRING_REDIS_USERNAME:-}
      SPRING_REDIS_PASSWORD: ${SPRING_REDIS_PASSWORD:-}
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_DDL_AUTO: ${SPRING_JPA_DDL_AUTO:-update}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      SWAGGER_USERNAME: ${SWAGGER_USERNAME:-admin}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD:-swagger@123}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    networks:
      - ecp_network
    restart: always

  admin:
    image: ghcr.io/thanhnguyenhoang171/ecp/ecp-admin:latest
    container_name: ecp_admin
    ports:
      - '8081:80'
    environment:
      NEXT_PUBLIC_ADMIN_API_URL: ${NEXT_PUBLIC_ADMIN_API_URL:-http://api:9090/api}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://api:9090/api}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    networks:
      - ecp_network
    restart: always

  storefront:
    image: ghcr.io/thanhnguyenhoang171/ecp/ecp-storefront:latest
    container_name: ecp_storefront
    ports:
      - '3000:3000'
    environment:
      STOREFRONT_INTERNAL_API_URL: ${STOREFRONT_INTERNAL_API_URL:-http://api:9090/api}
      NEXT_PUBLIC_STOREFRONT_API_URL: ${NEXT_PUBLIC_STOREFRONT_API_URL:-/api}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_STOREFRONT_API_URL:-/api}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    networks:
      - ecp_network
    restart: always

networks:
  ecp_network:
    driver: bridge
