spring.application.name=ecp_api
server.port=${SERVER_PORT:9090}
server.servlet.context-path=${SERVER_CONTEXT_PATH:/api}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MongoDB
spring.data.mongodb.uri=${SPRING_MONGODB_URI}

# Profiles
# Mặc định chạy profile local nếu không cấu hình gì thêm
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:none}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Jackson
spring.jackson.time-zone=GMT+7

# Redis
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

# Pagination
spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=1000

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}
app.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

# Swagger
springdoc.swagger-ui.persistAuthorization=true

#Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
