spring.application.name=ecp_api
server.port=${SERVER_PORT:9090}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/ecp_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:142857}

# MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:142857@localhost:27017/ecp_mongo?authSource=admin}

# Profiles
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
